networks:
  edge_net:
    external: true
    name: tienda3d_edge_net

services:
  orset_web:
    build: .
    container_name: orset_web
    restart: unless-stopped
    networks:
      - edge_net
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
